In [2]:
import numpy as np

this is 0d tensor 

In [3]:
a = np.array(4)
print(a)

4


this is 1d Tensor

In [4]:
b = [1,2,3,4]

In [5]:
print(b)
b

[1, 2, 3, 4]


[1, 2, 3, 4]

In [6]:
arr = np.array([1,2,3,4])

In [7]:
arr
print(arr)

[1 2 3 4]


In [8]:
arr.ndim

1

ADDING MULTIPLE SCALAR WILL TAKE YOU TO VECTOR 

2D TENSOR 

In [9]:
mat = np.array(([1,2,3],[4,5,6],[7,8,9]))

In [10]:
print(mat)
mat.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

In [11]:
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
